[package]
name = "spctr"
version = "0.1.0"
authors = ["Satoshi Amemiya <satoshi_amemiya@voyagegroup.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
nom = "5.1.3"
anyhow = "1.0.32"

# [profile.release]
# debug = true
